name: antwork
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.0.5
  flutter_svg: ^2.0.7
  dots_indicator: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.3

flutter:

  uses-material-design: true


  assets:
    - assets/logo/
    - assets/icons/
    - assets/images/

  fonts:
    - family: kanit
      fonts:
        - asset: assets/google_fonts/Kanit-Regular.ttf

