name: antwork
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.0.5
  flutter_svg: ^2.0.9
  dots_indicator: ^3.0.0
  buttons_tabbar: ^1.3.8
  readmore: ^2.2.0
  percent_indicator: ^4.2.3
  loading_animation_widget: ^1.2.0+4
  syncfusion_flutter_charts: ^23.1.43
  badges: ^3.1.2
  intl: ^0.18.1
  dropdown_button2: ^2.3.9
  file_picker: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/logo/
    - assets/icons/
    - assets/images/

  fonts:
    - family: kanit
      fonts:
        - asset: assets/google_fonts/Kanit-Regular.ttf

